// mazeGlue.js
// This is the JavaScript glue layer that wraps the Emscripten-compiled WebAssembly module.
// It provides a clean, high-level API for maze generation and solving.

// Global reference to the loaded WASM module instance
let Module = null;

/**
 * Initialize the maze WASM module.
 * This loads the compiled maze.js/maze.wasm and sets up the C++ functions for JS use.
 * Must be called once before calling any other functions.
 */
export async function initMaze() {
  // maze.js (generated by Emscripten with MODULARIZE=1) defines a global MazeModule
  // variable (loaded by the <script> tag in index.html).
  // MazeModule is a factory function that returns a Promise resolving to the Module instance.
  if (!globalThis.MazeModule) {
    throw new Error('MazeModule not found. Make sure maze.js is loaded via <script> tag.');
  }
  Module = await globalThis.MazeModule();
  console.log('Maze module initialized.');
}

/**
 * Generate a maze of the given dimensions using recursive backtracker.
 * @param {number} width - Number of columns
 * @param {number} height - Number of rows
 * @param {number} seed - Random seed (0 = use system time for random generation)
 * @returns {Object} { width, height, cells, steps } — cells is final wall bitmasks; steps
 *   replay generation (STATE_GEN_FROM/TO/BACK, then START/END).
 */
export function generateMaze(width, height, seed = 0) {
  if (!Module) throw new Error('Maze module not initialized. Call initMaze() first.');

  // Call the C++ generate function
  Module._generate(width, height, seed);

  // Read back the grid dimensions and cell array
  const w = Module._get_width();
  const h = Module._get_height();
  const cellsPtr = Module._get_cells_ptr();

  // Create a typed array view of the WASM memory at cellsPtr for w*h integers.
  // HEAP32 is a Int32Array view of the WASM linear memory (32-bit integers).
  const cells = new Int32Array(Module.HEAP32.buffer, cellsPtr, w * h);

  // Return a copy so the user gets a stable snapshot (not affected by future WASM ops).
  const steps = readStepsFromModule();
  return { width: w, height: h, cells: Array.from(cells), steps };
}

/**
 * Solve the maze using BFS (breadth-first search).
 * Finds the shortest path from start to end.
 * @param {number} startCol - Starting column (x)
 * @param {number} startRow - Starting row (y)
 * @param {number} endCol - Ending column (x)
 * @param {number} endRow - Ending row (y)
 * @returns {Array} Steps as [{ col, row, state }, ...].
 *   state: 0 = VISITED, 1 = FRONTIER, 2 = PATH, 3 = START, 4 = END
 */
export function solveBFS(startCol, startRow, endCol, endRow) {
  if (!Module) throw new Error('Maze module not initialized. Call initMaze() first.');

  // Call the C++ solve_bfs function
  Module._solve_bfs(startCol, startRow, endCol, endRow);

  // Read back the steps
  return readStepsFromModule();
}

/**
 * Solve the maze using DFS (depth-first search).
 * Does NOT guarantee shortest path, but visually explores with a single tendril.
 * @param {number} startCol - Starting column (x)
 * @param {number} startRow - Starting row (y)
 * @param {number} endCol - Ending column (x)
 * @param {number} endRow - Ending row (y)
 * @returns {Array} Steps as [{ col, row, state }, ...].
 */
export function solveDFS(startCol, startRow, endCol, endRow) {
  if (!Module) throw new Error('Maze module not initialized. Call initMaze() first.');

  // Call the C++ solve_dfs function
  Module._solve_dfs(startCol, startRow, endCol, endRow);

  // Read back the steps
  return readStepsFromModule();
}

/**
 * Solve the maze using A* (A-star).
 * Guaranteed shortest path and typically faster than BFS due to heuristic guidance.
 * @param {number} startCol - Starting column (x)
 * @param {number} startRow - Starting row (y)
 * @param {number} endCol - Ending column (x)
 * @param {number} endRow - Ending row (y)
 * @returns {Array} Steps as [{ col, row, state }, ...].
 */
export function solveAStar(startCol, startRow, endCol, endRow) {
  if (!Module) throw new Error('Maze module not initialized. Call initMaze() first.');

  // Call the C++ solve_astar function (if exported; see the emcc command)
  if (Module._solve_astar) {
    Module._solve_astar(startCol, startRow, endCol, endRow);
    return readStepsFromModule();
  } else {
    throw new Error('A* solver not exported. Add _solve_astar to EXPORTED_FUNCTIONS.');
  }
}

/**
 * Helper: read the step buffer from WASM memory and convert to an array of objects.
 * Steps are stored as a flat array of ints: [col, row, state, col, row, state, ...]
 * We parse them into { col, row, state } objects.
 * @private
 * @returns {Array} Steps as [{ col, row, state }, ...]
 */
function readStepsFromModule() {
  const stepsPtr = Module._get_steps_ptr();
  const stepsSize = Module._get_steps_size();

  // Create a typed array view of the step buffer (stepsSize ints starting at stepsPtr).
  const stepsArray = new Int32Array(Module.HEAP32.buffer, stepsPtr, stepsSize);

  // Parse triples (col, row, state) into objects.
  const steps = [];
  for (let i = 0; i < stepsSize; i += 3) {
    steps.push({
      col: stepsArray[i],
      row: stepsArray[i + 1],
      state: stepsArray[i + 2]
    });
  }

  return steps;
}

/**
 * State constants (must match the C++ enum values in maze.cpp).
 */
export const STATE_VISITED = 0;
export const STATE_FRONTIER = 1;
export const STATE_PATH = 2;
export const STATE_START = 3;
export const STATE_END = 4;
/** Generation: current cell before carving (pair with STATE_GEN_TO) */
export const STATE_GEN_FROM = 5;
/** Generation: neighbor cell after carving */
export const STATE_GEN_TO = 6;
/** Generation: backtrack (stack pop) from this cell */
export const STATE_GEN_BACK = 7;
